# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.5
mixin_extras_version=0.3.6

# mod
mod_id=amphitheremod
mod_name=Amphithere Mod
mod_version=1.0.3
mod_author=["Iqury"]
mod_description=Adds new features to Amphitheres: Inventory, Armor, Male/Female Amphitheres, Breeding Logic, Variant Selection After Breeding (gets parents 1/2 variant or chooses a random variant from the pool), New Variants, New Food, Small Fixes. Includes support for Classy Hats and SetBonus (Silver Armor gets Cure with Potion Core).
mixin_loader_class=amphitheremod.AmphithereModPlugin

# dependencies
fermiumbooter_version=968474:6741950
ice_and_fire_version=888556:6596246
llibrary_version=243298:3116493
classy_hats=281125:2722339
